import { request, createAxios } from '@/utils'

const chatRequest = createAxios({
  baseURL: import.meta.env.VITE_BASE_API,
  timeout: 120000,
})

export default {
  getHistory: () => request.get('/chat/history'),
  sendMessage: (data = {}) => chatRequest.post('/chat/chat', data),
  clearHistory: () => request.delete('/chat/history'),
  getModels: () => request.get('/chat/models'),
  agentChat: (data = {}) => chatRequest.post('/chat/agent', data),
  getAgentMemory: () => request.get('/chat/memory'),
  clearAgentMemory: () => request.delete('/chat/memory'),
  addDocuments: (data = {}) => request.post('/chat/documents', data),
  clearDocuments: (params = {}) => request.delete('/chat/documents', { params }),
  getDocumentStats: () => request.get('/chat/documents/stats'),
  searchDocuments: (data = {}) => request.post('/chat/documents/search', data),
  listDocuments: (params = {}) => request.get('/chat/documents/list', { params }),
  getDocumentDetail: (params = {}) => request.get('/chat/documents/detail', { params }),
  uploadDocuments: (formData) => request.post('/chat/upload', formData),
  getTodoList: (params = {}) => request.get('/chat/todos', { params }),
  createTodo: (data = {}) => request.post('/chat/todos', data),
  toggleTodo: (data = {}) => request.put('/chat/todos/toggle', data),
  updateTodo: (data = {}) => request.put('/chat/todos', data),
  deleteTodo: (params = {}) => request.delete('/chat/todos', { params }),
  clearCompletedTodos: () => request.delete('/chat/todos/completed'),
  getChatHistoryList: (params = {}) => request.get('/chat/history/list', { params }),
  createChatHistory: (data = {}) => request.post('/chat/history/create', data),
  updateChatHistory: (data = {}) => request.post('/chat/history/update', data),
  deleteChatHistory: (params = {}) => request.delete('/chat/history/delete', { params }),
  getFeedbackList: () => request.get('/chat/feedback'),
  getLowRatingFeedback: (params = {}) => request.get('/chat/feedback/low-rating', { params }),
  getConversations: () => request.get('/chat/conversations'),
  createConversation: (data = {}) => request.post('/chat/conversations', data),
  renameConversation: (data = {}) => request.put('/chat/conversations/rename', data),
  deleteConversation: (params = {}) => request.delete('/chat/conversations/delete', { params }),
  getConversationMessages: (convId) => request.get(`/chat/conversations/${convId}/messages`),
  getRecentConversations: (params = {}) => request.get('/chat/conversations/recent', { params }),

  getTrackerApplications: (params = {}) => request.get('/chat/tracker/applications', { params }),
  createTrackerApplication: (data = {}) => request.post('/chat/tracker/applications', data),
  getTrackerApplication: (appId) => request.get(`/chat/tracker/applications/${appId}`),
  updateTrackerApplication: (data = {}) => request.put('/chat/tracker/applications', data),
  moveTrackerApplication: (data = {}) => request.put('/chat/tracker/applications/move', data),
  deleteTrackerApplication: (params = {}) => request.delete('/chat/tracker/applications', { params }),
  getTrackerStats: () => request.get('/chat/tracker/applications/stats'),

  getInterviewSessions: () => request.get('/chat/interview-sim/sessions'),
  createInterviewSession: (data = {}) => request.post('/chat/interview-sim/sessions', data),
  getInterviewSession: (sessionId) => request.get(`/chat/interview-sim/sessions/${sessionId}`),
  interviewChat: (data = {}) => request.post('/chat/interview-sim/sessions/chat', data),
  evaluateInterview: (data = {}) => request.post('/chat/interview-sim/sessions/evaluate', data),
  deleteInterviewSession: (params = {}) => request.delete('/chat/interview-sim/sessions', { params }),

  getResumeTemplates: () => request.get('/chat/resume-export/templates'),
  generateResume: (data = {}) => request.post('/chat/resume-export/generate', data),
  exportResumeDocx: (data = {}) => request.post('/chat/resume-export/export/docx', data, { responseType: 'blob' }),
  exportResumeText: (data = {}) => request.post('/chat/resume-export/export/text', data),
  getResumeExports: () => request.get('/chat/resume-export/exports'),
  downloadResumeExport: (filename) => request.get(`/chat/resume-export/download/${filename}`, { responseType: 'blob' }),

  getDashboardOverview: () => request.get('/chat/dashboard/overview'),
  getTrackerChart: () => request.get('/chat/dashboard/tracker-chart'),
  getWeeklyActivity: () => request.get('/chat/dashboard/weekly-activity'),
}
